import {
  bytes,
  createActiveFS,
  dir,
  fsTree,
  json,
  text
} from "@activefs/core";
import { startActiveFSServer } from "@activefs/source-http";

export function createHelloSourceTree() {
  return fsTree({
    "/README.txt": text("Hello from an ActiveFS Source API tree.\n", { type: "text/plain" }),
    notes: dir({
      "source-api.txt": text("This file is generated by examples/hello-source.\n", { type: "text/plain" }),
      "change-me.txt": text("Edit examples/hello-source/src/index.ts, rebuild, and restart the server.\n", { type: "text/plain" })
    }),
    data: dir({
      "status.json": json(() => ({
        schemaVersion: 1,
        source: "hello-source",
        status: "ready",
        checkedAt: new Date().toISOString()
      }))
    }),
    bin: dir({
      "sample.bin": bytes(new Uint8Array([0, 1, 2, 3, 255]))
    })
  }, {
    name: "hello-source",
    capabilities: { search: true, searchable: true }
  });
}

export async function startHelloSourceServer(port = Number(process.env.PORT ?? 3999)) {
  return startActiveFSServer({
    port,
    tree: createHelloSourceTree(),
    handshake: {
      server: { name: "hello-source", version: "1.0.0" },
      workspace: {
        displayName: "Hello Source",
        suggestedMountPath: "/repo"
      },
      cache: { directoryTtlMs: 60_000 }
    }
  });
}

export async function runHelloSourceExample() {
  const fs = createActiveFS().mount("/", createHelloSourceTree());
  const entries = await fs.list({}, "/");
  const readme = await fs.read({}, "/README.txt");
  const search = await fs.search({}, "/", { pattern: "generated" });

  return {
    entries: entries.map((entry) => entry.path).sort(),
    readme: textContent(readme.content),
    matches: search.matches.map((match) => `${match.path}:${match.line ?? 0}`)
  };
}

function textContent(content: string | Uint8Array): string {
  return typeof content === "string" ? content : new TextDecoder().decode(content);
}

if (import.meta.url === `file://${process.argv[1]}`) {
  if (process.argv.includes("--once")) {
    const result = await runHelloSourceExample();
    console.log(`hello-source entries: ${result.entries.join(", ")}`);
    console.log(`hello-source read: ${result.readme.trim()}`);
    console.log(`hello-source matches: ${result.matches.join(", ")}`);
  } else {
    const server = await startHelloSourceServer();
    console.log(`ActiveFS hello source listening at ${server.url}`);
    console.log("Try: activefs remote add repo " + server.url);
  }
}
